MTMFTransformer:
    ko,species:
        n_layers: 1
        num_bottleneck: 8
        batch_size: 16
        lr: 1e-5
FT:
    ko:
        'n_blocks': 1
        'lr': 0.00001
        'batch_size': 8
    species:
        'n_blocks': 2
        'lr': 0.00001
        'batch_size': 4
    ks:
        'n_blocks': 2
        'lr': 0.0001
        'batch_size': 16
MBT:
    ko,species:
        n_layers: 2
        m_layers: 1
        num_bottleneck: 4
        hidden_size: 32
        lr: 6e-5
        batch_size: 8
