MTMFTransformer:
    ko,species:
        n_layers: 1
        num_bottleneck: 4
        use_bottleneck: True
        batch_size: 8
        lr: 1e-3
FT:
    ko:
        'n_blocks': 1
        'lr': 0.0001
        'batch_size': 16
    species:
        'n_blocks': 2
        'lr': 0.0001
        'batch_size': 8
    ks:
        'n_blocks': 3
        'lr': 0.0001
        'batch_size': 8
FT-Concat:
    ko,species:
FT-Vote:
    ko,species:
MBT:
    ko,species:
        n_layers: 2
        m_layers: 1
        num_bottleneck: 4
        hidden_size: 0
        lr: 6e-5
        batch_size: 4