MTMFTransformer:
    ko,species:
        n_layers: 1
        num_bottleneck: 16
        batch_size: 32
        lr: 0.001
FT:
    ko:
        'n_blocks': 3
        'lr': 0.001
        'batch_size': 8
    species:
        'n_blocks': 1
        'lr': 0.001
        'batch_size': 8
    ks:
        'n_blocks': 1
        'lr': 0.0001
        'batch_size': 4
MBT:
    ko,species:
        n_layers: 1
        m_layers: 1
        num_bottleneck: 4
        hidden_size: 0
        lr: 1e-3
        batch_size: 8