MTMFTransformer:
    ko,species:
        n_layers: 2
        num_bottleneck: 16
        batch_size: 8
        lr: 0.0001
MBT:
    ko,species:
        n_layers: 2
        m_layers: 1
        num_bottleneck: 4
        hidden_size: 0
        lr: 1e-3
        batch_size: 8
FT-Concat:
    ko,species:
        'n_blocks': 1
        'lr': 0.0001
        'batch_size': 4
FT-Vote:
    ko,species:
        'n_blocks': 1
        'lr': 0.001
        'batch_size': 8