MTMFTransformer:
    ko,species:
        n_layers: 1
        num_bottleneck: 16
        batch_size: 32
        lr: 5e-6
FT:
    ko:
        'n_blocks': 2
        'lr': 0.0001
        'batch_size': 16
    species:
        'n_blocks': 2
        'lr': 0.001
        'batch_size': 16
    ks:
        'n_blocks': 2
        'lr': 0.0001
        'batch_size': 16
MBT:
    ko,species:
        n_layers: 2
        m_layers: 2
        num_bottleneck: 4
        hidden_size: 0
        lr: 1e-3
        batch_size: 4
