MTMFTransformer:
    ko,species:
        n_layers: 2
        num_bottleneck: 8
        batch_size: 16
        lr: 0.001
MBT:
    ko,species:
        n_layers: 3
        m_layers: 2
        num_bottleneck: 4
        hidden_size: 0
        lr: 0.0001
        batch_size: 4
FT-Concat:
    ko,species:
        'n_blocks': 2
        'lr': 0.0001
        'batch_size': 8
FT-Vote:
    ko,species:
        'n_blocks': 3
        'lr': 0.0001
        'batch_size': 4